"""empty message

Revision ID: 025be0192f95
Revises: 23a40686f341
Create Date: 2025-03-05 11:01:13.588994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025be0192f95'
down_revision: Union[str, None] = '23a40686f341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_attempt', sa.Column('decision', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_attempt', 'decision')
    # ### end Alembic commands ###
