"""qa rejection rate

Revision ID: 07ddf2065a22
Revises: 93647887eb1a
Create Date: 2025-02-03 14:49:25.730835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ddf2065a22'
down_revision: Union[str, None] = '93647887eb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_member', sa.Column('total_tasks_accepted', sa.Integer(), nullable=False))
    op.add_column('qa_member', sa.Column('total_tasks_rejected', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_member', 'total_tasks_rejected')
    op.drop_column('qa_member', 'total_tasks_accepted')
    # ### end Alembic commands ###
