"""initial pw for qa

Revision ID: 215172ee7747
Revises: 6fd61d4eb64a
Create Date: 2025-02-04 00:35:26.994083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215172ee7747'
down_revision: Union[str, None] = '6fd61d4eb64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_member', sa.Column('initial_password', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_member', 'initial_password')
    # ### end Alembic commands ###
