"""updated Job

Revision ID: 25837c2e5709
Revises: 8ec5ff84b746
Create Date: 2025-02-18 20:09:15.377627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25837c2e5709'
down_revision: Union[str, None] = '8ec5ff84b746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('job', sa.Column('is_assessment', sa.Boolean(), nullable=False))
    op.add_column('job', sa.Column('is_assessment', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'is_assessment')
    # ### end Alembic commands ###
