"""empty message

Revision ID: 27371f8394dc
Revises: 025be0192f95
Create Date: 2025-03-06 19:54:39.470612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27371f8394dc'
down_revision: Union[str, None] = '025be0192f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freelancer_language_pair', sa.Column('complete_task', sa.Integer(), nullable=True))
    op.add_column('freelancer_language_pair', sa.Column('rejected_task', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freelancer_language_pair', 'rejected_task')
    op.drop_column('freelancer_language_pair', 'complete_task')
    # ### end Alembic commands ###
