"""empty message

Revision ID: 3fea4535cde7
Revises: c2d867ec8b33
Create Date: 2025-03-10 16:29:24.703819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fea4535cde7'
down_revision: Union[str, None] = 'c2d867ec8b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal', sa.Column('proof_of_payment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal', 'proof_of_payment')
    # ### end Alembic commands ###
