"""added job title

Revision ID: 5d4bbfe77b95
Revises: 255bdf5c36dd
Create Date: 2025-01-31 16:45:28.631895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4bbfe77b95'
down_revision: Union[str, None] = '255bdf5c36dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_title')
    # ### end Alembic commands ###
