"""delete tasks for job deletion

Revision ID: 6fd61d4eb64a
Revises: 07ddf2065a22
Create Date: 2025-02-03 18:58:11.636587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd61d4eb64a'
down_revision: Union[str, None] = '07ddf2065a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
