"""attemptable

Revision ID: 73dd97bb9304
Revises: 25837c2e5709
Create Date: 2025-02-19 15:29:16.203550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dd97bb9304'
down_revision: Union[str, None] = '25837c2e5709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_attempt',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('submission_text', sa.String(), nullable=True),
    sa.Column('attempt_status', sa.Enum('UNDER_REVIEW', 'COMPLETE', name='ass_task_status'), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.freelancer_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_assessment_attempt_freelancer_id'), 'assessment_attempt', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempt_task_id'), 'assessment_attempt', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_attempt_task_id'), table_name='assessment_attempt')
    op.drop_index(op.f('ix_assessment_attempt_freelancer_id'), table_name='assessment_attempt')
    op.drop_table('assessment_attempt')
    # ### end Alembic commands ###
