"""...

Revision ID: 7ca1c270e229
Revises: 
Create Date: 2025-01-28 15:58:38.420728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca1c270e229'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('freelancer',
    sa.Column('freelancer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_withdrawn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pending_withdrawal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('freelancer_id')
    )
    op.create_table('language',
    sa.Column('language_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('language_id')
    )
    op.create_table('qa_member',
    sa.Column('qa_member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('tasks_reviewed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('qa_member_id')
    )
    op.create_table('freelancer_language_pair',
    sa.Column('language_pair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.freelancer_id'], ),
    sa.ForeignKeyConstraint(['source_language_id'], ['language.language_id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('language_pair_id')
    )
    op.create_index(op.f('ix_freelancer_language_pair_freelancer_id'), 'freelancer_language_pair', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_freelancer_language_pair_source_language_id'), 'freelancer_language_pair', ['source_language_id'], unique=False)
    op.create_index(op.f('ix_freelancer_language_pair_target_language_id'), 'freelancer_language_pair', ['target_language_id'], unique=False)
    op.create_table('issue_report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.Enum('WRONG_SOURCE_LANGUAGE', 'PAYMENT_DELAY', 'ACCURACY_APPEAL', 'OTHER', name='issuetype'), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('report_status', sa.Enum('UNDER_REVIEW', 'PROCEED', name='reportstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.freelancer_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_issue_report_admin_id'), 'issue_report', ['admin_id'], unique=False)
    op.create_index(op.f('ix_issue_report_freelancer_id'), 'issue_report', ['freelancer_id'], unique=False)
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('max_time_per_task', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('task_price', sa.Float(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_language_id'], ['language.language_id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_job_source_language_id'), 'job', ['source_language_id'], unique=False)
    op.create_index(op.f('ix_job_target_language_id'), 'job', ['target_language_id'], unique=False)
    op.create_table('withdrawal',
    sa.Column('withdrawal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('PAYPAL', 'PAYONEER', 'KPAY', 'WAVEPAY', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('withdrawal_status', sa.Enum('UNDER_PROCESSING', 'PROCESSED', name='withdrawalstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.freelancer_id'], ),
    sa.PrimaryKeyConstraint('withdrawal_id')
    )
    op.create_index(op.f('ix_withdrawal_admin_id'), 'withdrawal', ['admin_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_freelancer_id'), 'withdrawal', ['freelancer_id'], unique=False)
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=True),
    sa.Column('max_time_per_task', sa.Integer(), nullable=False),
    sa.Column('task_status', sa.Enum('OPEN', 'ASSIGNED_TO_FL', 'UNDER_REVIEW', 'COMPLETE', name='taskstatus'), nullable=False),
    sa.Column('assigned_freelancer_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('qa_assigned_id', sa.Integer(), nullable=True),
    sa.Column('qa_reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('task_price', sa.Float(), nullable=False),
    sa.Column('is_assessment', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('qa_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('qa_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_freelancer_id'], ['freelancer.freelancer_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.ForeignKeyConstraint(['qa_assigned_id'], ['qa_member.qa_member_id'], ),
    sa.ForeignKeyConstraint(['qa_reviewed_by_id'], ['qa_member.qa_member_id'], ),
    sa.ForeignKeyConstraint(['source_language_id'], ['language.language_id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['freelancer.freelancer_id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['language.language_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_assigned_freelancer_id'), 'task', ['assigned_freelancer_id'], unique=False)
    op.create_index(op.f('ix_task_job_id'), 'task', ['job_id'], unique=False)
    op.create_index(op.f('ix_task_qa_assigned_id'), 'task', ['qa_assigned_id'], unique=False)
    op.create_index(op.f('ix_task_qa_reviewed_by_id'), 'task', ['qa_reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_task_source_language_id'), 'task', ['source_language_id'], unique=False)
    op.create_index(op.f('ix_task_submitted_by_id'), 'task', ['submitted_by_id'], unique=False)
    op.create_index(op.f('ix_task_target_language_id'), 'task', ['target_language_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_target_language_id'), table_name='task')
    op.drop_index(op.f('ix_task_submitted_by_id'), table_name='task')
    op.drop_index(op.f('ix_task_source_language_id'), table_name='task')
    op.drop_index(op.f('ix_task_qa_reviewed_by_id'), table_name='task')
    op.drop_index(op.f('ix_task_qa_assigned_id'), table_name='task')
    op.drop_index(op.f('ix_task_job_id'), table_name='task')
    op.drop_index(op.f('ix_task_assigned_freelancer_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_withdrawal_freelancer_id'), table_name='withdrawal')
    op.drop_index(op.f('ix_withdrawal_admin_id'), table_name='withdrawal')
    op.drop_table('withdrawal')
    op.drop_index(op.f('ix_job_target_language_id'), table_name='job')
    op.drop_index(op.f('ix_job_source_language_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_issue_report_freelancer_id'), table_name='issue_report')
    op.drop_index(op.f('ix_issue_report_admin_id'), table_name='issue_report')
    op.drop_table('issue_report')
    op.drop_index(op.f('ix_freelancer_language_pair_target_language_id'), table_name='freelancer_language_pair')
    op.drop_index(op.f('ix_freelancer_language_pair_source_language_id'), table_name='freelancer_language_pair')
    op.drop_index(op.f('ix_freelancer_language_pair_freelancer_id'), table_name='freelancer_language_pair')
    op.drop_table('freelancer_language_pair')
    op.drop_table('qa_member')
    op.drop_table('language')
    op.drop_table('freelancer')
    op.drop_table('admin')
    # ### end Alembic commands ###
