"""update qa member

Revision ID: 8ec5ff84b746
Revises: 215172ee7747
Create Date: 2025-02-04 13:37:05.199863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec5ff84b746'
down_revision: Union[str, None] = '215172ee7747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_member', 'total_tasks_accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_member', sa.Column('total_tasks_accepted', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
