"""task on delete cascade

Revision ID: b1209bf7950e
Revises: d6fc925a7184
Create Date: 2025-01-31 21:38:11.330338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1209bf7950e'
down_revision: Union[str, None] = 'd6fc925a7184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'total_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('task_job_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_job_id_fkey', 'task', 'job', ['job_id'], ['job_id'])
    op.alter_column('job', 'total_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
