"""empty message

Revision ID: b65cdd887259
Revises: d1ce6c44abe1
Create Date: 2025-03-12 16:22:41.074387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65cdd887259'
down_revision: Union[str, None] = 'd1ce6c44abe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_report', sa.Column('source_language_id', sa.Integer(), nullable=True))
    op.add_column('issue_report', sa.Column('target_language_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_report', 'target_language_id')
    op.drop_column('issue_report', 'source_language_id')
    # ### end Alembic commands ###
