"""empty message

Revision ID: c2d867ec8b33
Revises: 27371f8394dc
Create Date: 2025-03-10 12:25:41.179969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2d867ec8b33'
down_revision: Union[str, None] = '27371f8394dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal', sa.Column('paypal_link', sa.String(), nullable=True))
    op.add_column('withdrawal', sa.Column('payoneer_email', sa.String(), nullable=True))
    op.add_column('withdrawal', sa.Column('wavepay_phone', sa.String(), nullable=True))
    op.add_column('withdrawal', sa.Column('kpay_phone', sa.String(), nullable=True))
    op.add_column('withdrawal', sa.Column('account_holder_name', sa.String(), nullable=True))
    op.add_column('withdrawal', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('withdrawal', sa.Column('account_number', sa.String(), nullable=True))
    op.alter_column('withdrawal', 'payment_method',
               existing_type=postgresql.ENUM('PAYPAL', 'PAYONEER', 'KPAY', 'WAVEPAY', name='paymentmethod'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdrawal', 'payment_method',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PAYPAL', 'PAYONEER', 'KPAY', 'WAVEPAY', name='paymentmethod'),
               existing_nullable=False)
    op.drop_column('withdrawal', 'account_number')
    op.drop_column('withdrawal', 'bank_name')
    op.drop_column('withdrawal', 'account_holder_name')
    op.drop_column('withdrawal', 'kpay_phone')
    op.drop_column('withdrawal', 'wavepay_phone')
    op.drop_column('withdrawal', 'payoneer_email')
    op.drop_column('withdrawal', 'paypal_link')
    # ### end Alembic commands ###
