"""empty message

Revision ID: d1ce6c44abe1
Revises: edd554441709
Create Date: 2025-03-12 16:12:34.743267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ce6c44abe1'
down_revision: Union[str, None] = 'edd554441709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_report', sa.Column('taskId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_report', 'taskId')
    # ### end Alembic commands ###
