"""empty message

Revision ID: edd554441709
Revises: 3ff12b9ca244
Create Date: 2025-03-12 15:45:45.998676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd554441709'
down_revision: Union[str, None] = '3ff12b9ca244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_report', sa.Column('withdrawalId', sa.Integer(), nullable=True))
    op.add_column('issue_report', sa.Column('description', sa.String(), nullable=True))
    op.add_column('issue_report', sa.Column('documentationUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_report', 'documentationUrl')
    op.drop_column('issue_report', 'description')
    op.drop_column('issue_report', 'withdrawalId')
    # ### end Alembic commands ###
