"""job status

Revision ID: f51a4654ef66
Revises: b1209bf7950e
Create Date: 2025-02-01 18:15:02.660823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.schemas.enums import JobStatus

# revision identifiers, used by Alembic.
revision: str = 'f51a4654ef66'
down_revision: Union[str, None] = 'b1209bf7950e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create ENUM type
    op.execute("CREATE TYPE jobstatus AS ENUM ('IN_PROGRESS', 'COMPLETED', 'CLOSED')")

    # Add column as nullable first
    op.add_column('task', sa.Column('job_status', sa.Enum(JobStatus), nullable=True))

    # Set a default value for existing rows (choose an appropriate default)
    op.execute("UPDATE task SET job_status = 'IN_PROGRESS'")

    # Make the column non-nullable
    op.alter_column('task', 'job_status', nullable=False)

    # Add constraint
    op.execute("ALTER TABLE task ADD CONSTRAINT job_status_check CHECK (job_status IN ('IN_PROGRESS', 'COMPLETED', 'CLOSED'))")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'job_status')
    # ### end Alembic commands ###
